"""Added classes field

Revision ID: c8b03682d1b1
Revises: 9b0893910c1e
Create Date: 2025-03-28 17:32:52.753361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8b03682d1b1'
down_revision: Union[str, None] = '9b0893910c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('classes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'classes')
    # ### end Alembic commands ###
